excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - RushCaptainUITests
disabled_rules:
  - trailing_whitespace
  - todo
  - vertical_parameter_alignment


line_length:
  ignores_function_declarations: true
  ignores_comments: true
  ignores_interpolated_strings: true
