# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
    lane :release do
		
		# Increment the build number (not the version number)
		increment_build_number(xcodeproj: "Rush Captain.xcodeproj")

		# Duh
		build_app

		# Upload to app store and wait for processing
		upload_to_app_store(
		    force: true, # Set to true to skip PDF verification
			automatic_release: true,
		)
    end
    lane :beta do
		# Increment the build number (not the version number)
		increment_build_number(xcodeproj: "Rush Captain.xcodeproj")

		# Duh
		build_app

		# Upload to testflight and wait for processing
		upload_to_testflight(
		    force: true, # Set to true to skip PDF verification
		)
	end
end